# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Use Python 3.10'
- script: python3 -m pip install pipenv
  displayName: 'Install pipenv'

- script: python3 -m pipenv sync --dev
  displayName: 'Set up pipenv environment'

- script: python3 -m pipenv run python -m flake8
  displayName: 'Run lint'
